### ISSUE TITLE
Header link not redirecting to home page

### ISSUE THREAD

**Issue by eapl-gemugami** [sorenpeter/timeline#37]
If you click on the Site Name or the logo, it takes you to `/` (base directory for the domain), not `/timeline/` (base for the Web app)
![image](https://github.com/user-attachments/assets/952abd6e-9cc7-4a13-b386-aedccc909e67)

Live URL: https://twtxt-sandbox.eapl.me/timeline/

**Comment by aelaraji** [comment]
I believe that's because the `/timeline` URI was meant to be part of a whole website where you have a for example a `Home` page where that Logo/Link takes you back to, an `About` page, a `Blog` one ...etc and then a `Timeline` etc. just like on @sorenpeter's personal website.

Then if timeline was served on a sub-domain instead of a sub-directory it would indeed take you to the timeline itself.

**Comment by eapl-gemugami** [comment]
I think it involves changing here
https://github.com/sorenpeter/timeline/blob/main/partials/header.php#L29

From `/` to `.`, I'll check if I can leave something useful for all
